name: Decrypt
description: decrypt
inputs:
  environment:
    description: environment
    required: true
  decrypt-pass:
    description: pass
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: decrypt
      shell: bash
      env:
        ENCRYPTED: a.${{ inputs.environment }}.encrypted
        PASS: ${{ inputs.decrypt-pass }}
      run: |
        cd src
        openssl aes-256-cbc -d -in ${ENCRYPTED} -out .env.${ENVIRONMENT} -pass pass:${PASS}
