name: Decrypt
description: decrypt
inputs:
  environment:
    description: environment
    required: true
  decrypt-pass:
    description: pass
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: debug
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        DECRYPT_PASS: ${{ inputs.decrypt-pass }}
      run: |
        echo ${{ inputs.environment }}
        echo ${{ inputs.decrypt-pass }}
        echo $ENVIRONMENT
        echo $DECRYPT_PASS
    - name: decrypt
      shell: bash
      env:
        AAA: ${{ inputs.environment }}
        ENCRYPTED: a.${{ inputs.environment }}.encrypted
        PASS: ${{ inputs.decrypt-pass }}
      run: |
        echo $AAA
        echo $ENCRYPTED
        echo $PASS
        cd src
        openssl aes-256-cbc -d -in ${ENCRYPTED} -out .env.${AAA} -pass pass:${PASS}
