name: called

on:
  workflow_call:
    secrets:
      test:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - run: |
          echo ${{ github.ref_name }}
