name: Test GitHub Actions

on:
  push:
    branches: ["main"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir ./dist-task-def
          echo hoge > ./dist-task-def/a-task-def.json
          echo fuga > ./dist-task-def/b-task-def.json

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-task-def
          path: |
            dist-task-def

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-task-def
      - run: |
          ls