name: called

on:
  workflow_call:
    inputs:
      test:
        required: true
        type: string
    outputs:
      test-a:
        value: ${{ jobs.job1.outputs.test-a }}
      test-b:
        value: ${{ jobs.job1.outputs.test-b }}

jobs:
  job1:
    name: hoge
    runs-on: ubuntu-latest
    outputs:
      test-a: ${{ steps.test.outputs.test-a }}
      test-b: ${{ steps.test.outputs.test-b }}
    steps:
      - uses: actions/checkout@v3

      - id: test
        run: |
          a=${{ inputs.test }}-a
          b=${{ inputs.test }}-b
          echo "test-a=$a.example.com@hoge/test:abc" >> $GITHUB_OUTPUT
          echo "test-b=$b.example.com@fuga/test:abc" >> $GITHUB_OUTPUT