name: called

on:
  workflow_call:
    secrets:
      test:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - run: |
          ls ${{ secrets.test }}
