name: Test GitHub Actions

on:
  push:
    branches: ["main"]

jobs:
  called:
    name: hoge
    runs-on: ubuntu-latest
    outputs:
      test-a: ${{ steps.test.outputs.test-a }}
      test-b: ${{ steps.test.outputs.test-b }}
    steps:
      - uses: actions/checkout@v3

      - id: test
        run: |
          a=${{ inputs.test }}-a
          b=${{ inputs.test }}-b
          echo "test-a=$a.example.com@hoge/test:abc" >> $GITHUB_OUTPUT
          echo "test-b=$b.example.com@fuga/test:abc" >> $GITHUB_OUTPUT

  test:
    needs: called
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo ${{ needs.called.outputs.test-a }}
          echo ${{ needs.called.outputs.test-b }}