name: called

on:
  workflow_call:
    inputs:
      test:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - run: |
          id: set-env
          echo "test=${{ secrets.TEST }}" >> $GITHUB_ENV
      - run: |
          ls ${{ env.test }}
