name: called

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Set main env
        if: github.ref_name == 'main'
        run: |
          echo "test=MAIN" >> $GITHUB_ENV
      
      - name: Set develop env
        if: github.ref_name == 'develop'
        run: |
          echo "test=DEVELOP" >> $GITHUB_ENV

      - run: |
          echo $test

  job3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set env
        run: |
          echo ENVIRONMENT=b >> $GITHUB_ENV
          echo PASS=hogefuga >> $GITHUB_ENV
      - name: debug
        run: |
          echo ${{ env.ENVIRONMENT }}
          echo ${{ env.PASS }}
      - name: Decrypt
        uses: ./.github/actions/decrypt
        with:
          decrypt-pass: ${{ env.PASS }}
          environment: ${{ env.ENVIRONMENT }}
