name: called

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Set main env
        if: github.ref_name == 'main'
        run: |
          echo "test=MAIN" >> $GITHUB_ENV
      
      - name: Set develop env
        if: github.ref_name == 'develop'
        run: |
          echo "test=DEVELOP" >> $GITHUB_ENV

      - run: |
          echo $test

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: test
        env:
          IMAGE_TAG: $GITHUB_SHA
        run: |
          echo $IMAGE_TAG
