name: Test GitHub Actions

on:
  push:
    branches: ["main"]

env:
  TEST: ${{ secrets.TEST }}

jobs:
  called:
    uses: ./.github/workflows/called.yml
    with:
      TEST: hoge

  test:
    needs: called
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo ${{ needs.called.outputs.test-a }}
          echo ${{ needs.called.outputs.test-b }}