name: Test GitHub Actions

on:
  push:
    branches: ["main"]

jobs:
#  test:
#    uses: ./.github/workflows/called.yml
#  job2:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - run: echo TEST=abc >> $GITHUB_ENV
#      - uses: ./.github/actions/test-action
#        with:
#          test: $TEST
  job3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd src
          openssl aes-256-cbc -e -in a.b.txt -out a.b.encrypted -pass pass:hoge
      - run: |
          echo ENVIRONMENT=b >> $GITHUB_ENV
          echo PASS=hoge >> $GITHUB_ENV
      - run: |
          cd src
          openssl aes-256-cbc -d -in a.${ENVIRONMENT}.encrypted -out .env.${ENVIRONMENT} -pass pass:${PASS} -md md5