name: Test GitHub Actions

on:
  push:
    branches: ["main"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "failure"
          exit 1

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "job2"

  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "job3"
  
  success:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    if: success()
    steps:
      - run: echo "success!"

  failure:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    if: failure()
    steps:
      - run: echo "failure!"