name: Test GitHub Actions

on:
  push:
    branches: ["main"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "job1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "job2 failure"
          exit 1
  
  success:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: success()
    steps:
      - run: echo "success!"

  failure:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: failure()
    steps:
      - run: echo "failure!"