name: Test GitHub Actions

on:
  push:
    branches: ["main"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "job1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "job2 failure"
          exit 1
  
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: success
        if: success()
        run: echo "success!"
      - name: failure
        if: failure()
        run: echo "failure!"
