name: Test GitHub Actions

on:
  push:
    branches: ["main", "develop"]

jobs:
  test:
    uses: ./.github/workflows/called.yml
    secrets: inherit
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_SHA